name: Pre-merge checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  lint-and-typecheck:
    name: Lint & Typecheck
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn install

      - name: Run eslint
        run: |
          yarn lint

      - name: Run tsc
        if: always() # This ensures tsc runs even if lint fails
        run: |
          yarn tsc

  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn install

      - name: Run tests
        run: |
          yarn test
