name: Pre-merge checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint-and-typecheck:
    name: Lint & Typecheck
    runs-on: ubuntu-22.04
    steps:
      - name: Install dev dependencies
        run: |
          npm install

      - name: Run pre-commit lint checks
        run: |
          yarn pre-commit-checks

      - name: Run tsc (TypeScript Compiler)
        run: |
          yarn tsc

  test:
    name: Run Playwright specs
    runs-on: ubuntu-22.04
    env:
      HOST: ${{ secrets.HOST }} # Staging environment URL
      EMAIL: ${{ secrets.EMAIL }} # Credentials for testing
      PASSWORD: ${{ secrets.PASSWORD }}
      NEW_INQUIRY_URL: ${{ secrets.NEW_INQUIRY_URL }}
    steps:
      - name: Install dev dependencies
        run: |
          npm install

      - name: Install Playwright browsers
        run: |
          npx playwright install

      - name: Run Playwright tests
        run: |
          npm test
