name: Pre-merge checks
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint-and-typecheck:
    name: Lint & Typecheck
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn install

      - name: Run eslint
        run: |
          yarn lint

      - name: Run pre-commit lint checks
        run: |
          yarn pre-commit-checks

      - name: Run tsc
        if: always()
        run: |
          yarn tsc

  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn install

      - name: Install Playwright browsers
        run: |
          npx playwright install

      - name: Run tests
        run: |
          yarn test
