name: Pre-merge checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint-and-typecheck:
    name: Lint & Typecheck
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v2
        with:
          repository: teamlawfty/internal_lawfty5 # Frontend repo
          ref: main # Ensure correct branch

      - name: Install frontend dependencies
        run: |
          yarn install

      - name: Run pre-commit lint checks (Frontend)
        run: |
          yarn pre-commit-checks

      - name: Run tsc (TypeScript Compiler for Frontend)
        run: |
          yarn tsc

  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    env:
      HOST: ${{ secrets.HOST }} # Staging environment URL
      EMAIL: ${{ secrets.EMAIL }} # Credentials and other environment variables
      PASSWORD: ${{ secrets.PASSWORD }}
      NEW_INQUIRY_URL: ${{ secrets.NEW_INQUIRY_URL }}
    steps:
      - name: Install frontend dependencies
        run: |
          yarn install

      - name: Install Playwright browsers
        run: |
          npx playwright install

      - name: Run Playwright tests
        run: |
          yarn test
