name: Pre-merge checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint-and-typecheck:
    name: Lint & Typecheck
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Run pre-commit lint checks
        run: |
          yarn pre-commit-checks

      - name: Run tsc (TypeScript Compiler)
        run: |
          yarn tsc

  test:
    name: Run Playwright specs
    runs-on: ubuntu-22.04
    env:
      HOST: ${{ secrets.HOST }}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      NEW_INQUIRY_URL: ${{ secrets.NEW_INQUIRY_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Install Playwright browsers
        run: |
          npx playwright install

      - name: Run Playwright tests
        run: |
          npm test
        imeout-minutes: 1
